# Generated by Django 4.2.24 on 2025-10-14 15:43

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figuras', to='EditorWebGeoespacial.capa')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_via',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cauces',
            fields=[
                ('figura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EditorWebGeoespacial.figura')),
                ('tipificacion', models.CharField(max_length=2)),
                ('longitud', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('largo_tramo', models.IntegerField()),
                ('capacidad_maxima', models.CharField(max_length=15)),
                ('pendiente', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            bases=('EditorWebGeoespacial.figura',),
        ),
        migrations.CreateModel(
            name='Grifos',
            fields=[
                ('figura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EditorWebGeoespacial.figura')),
                ('numero', models.IntegerField()),
                ('mm', models.IntegerField()),
            ],
            bases=('EditorWebGeoespacial.figura',),
        ),
        migrations.CreateModel(
            name='Microbasural',
            fields=[
                ('figura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EditorWebGeoespacial.figura')),
                ('direccion', models.CharField(max_length=20)),
                ('m2', models.IntegerField()),
                ('m3', models.IntegerField()),
                ('accesibilidad', models.CharField(choices=[('buena', 'BUENA'), ('regular', 'REGULAR'), ('mala', 'MALA')], max_length=10)),
                ('tipo_residuo', models.CharField(max_length=10)),
                ('observacion', models.TextField()),
            ],
            bases=('EditorWebGeoespacial.figura',),
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='figura',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.subcategoria'),
        ),
        migrations.CreateModel(
            name='Cuarteles_de_bomberos',
            fields=[
                ('figura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EditorWebGeoespacial.figura')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=20)),
                ('numeracion', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=11)),
                ('cerro_o_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.sector')),
                ('tipo_via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.tipo_de_via')),
            ],
            bases=('EditorWebGeoespacial.figura',),
        ),
    ]
