# Generated by Django 4.2.24 on 2025-10-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subclasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.subcategoria')),
            ],
        ),
        migrations.AddField(
            model_name='figura',
            name='subclasificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.subclasificacion'),
            preserve_default=False,
        ),
    ]
