# Generated by Django 4.2.24 on 2025-10-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0002_subclasificacion_figura_subclasificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figura',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='figura',
            name='subcategoria',
        ),
    ]
