# Generated by Django 4.2.24 on 2025-10-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0004_subclasificacion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclasificacion',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.subcategoria'),
        ),
    ]
