# Generated by Django 4.2.24 on 2025-10-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0005_alter_subclasificacion_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclasificacion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.categoria'),
        ),
    ]
