# Generated by Django 4.2.24 on 2025-10-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0006_alter_subclasificacion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclasificacion',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.categoria'),
            preserve_default=False,
        ),
    ]
