# Generated by Django 4.2.24 on 2025-10-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0007_alter_subclasificacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='atributos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subclasificacion',
            name='campos_config',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subclasificacion',
            name='tipo_geometria',
            field=models.CharField(choices=[('Point', 'Punto'), ('MultiLinestring', 'PoliLínea'), ('Polygon', 'Polígono')], default='', max_length=20),
        ),
    ]
