# Generated by Django 4.2.24 on 2025-10-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0008_figura_atributos_subclasificacion_campos_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclasificacion',
            name='tipo_geometria',
            field=models.CharField(choices=[('Point', 'Punto'), ('Linestring', 'PoliLínea'), ('Polygon', 'Polígono')], default='', max_length=20),
        ),
    ]
