# Generated by Django 4.2.24 on 2025-10-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0009_alter_subclasificacion_tipo_geometria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclasificacion',
            name='tipo_geometria',
            field=models.CharField(choices=[('Point', 'Punto'), ('LineString', 'PoliLínea'), ('Polygon', 'Polígono')], default='', max_length=20),
        ),
    ]
