# Generated by Django 4.2.24 on 2025-10-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0011_proyecto_subclasificacion_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subclasificacion',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='categoria',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.proyecto'),
            preserve_default=False,
        ),
    ]
