# Generated by Django 4.2.24 on 2025-10-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0012_remove_subclasificacion_proyecto_categoria_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.ManyToManyField(related_name='proyectos', to='EditorWebGeoespacial.categoria'),
        ),
    ]
