# Generated by Django 4.2.24 on 2025-10-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0013_remove_categoria_proyecto_proyecto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuarteles_de_bomberos',
            name='cerro_o_sector',
        ),
        migrations.RemoveField(
            model_name='cuarteles_de_bomberos',
            name='figura_ptr',
        ),
        migrations.RemoveField(
            model_name='cuarteles_de_bomberos',
            name='tipo_via',
        ),
        migrations.RemoveField(
            model_name='grifos',
            name='figura_ptr',
        ),
        migrations.RemoveField(
            model_name='microbasural',
            name='figura_ptr',
        ),
        migrations.DeleteModel(
            name='Cauces',
        ),
        migrations.DeleteModel(
            name='Cuarteles_de_bomberos',
        ),
        migrations.DeleteModel(
            name='Grifos',
        ),
        migrations.DeleteModel(
            name='Microbasural',
        ),
    ]
