# Generated by Django 4.2.24 on 2025-11-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0014_remove_cuarteles_de_bomberos_cerro_o_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
