# Generated by Django 4.2.24 on 2025-11-17 14:20

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EditorWebGeoespacial', '0015_proyecto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capa_importada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_geometria', models.CharField(max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capa_importada', to='EditorWebGeoespacial.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('atributos', models.JSONField(default=dict)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='EditorWebGeoespacial.capa_importada')),
            ],
        ),
        migrations.RemoveField(
            model_name='figura',
            name='capa',
        ),
        migrations.DeleteModel(
            name='Capa',
        ),
    ]
