# Generated by Django 4.2.24 on 2025-11-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0016_capa_importada_feature_remove_figura_capa_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capa_importada',
            unique_together={('proyecto', 'nombre')},
        ),
    ]
