# Generated by Django 4.2.24 on 2025-11-18 19:33

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EditorWebGeoespacial', '0017_alter_capa_importada_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figura',
            name='coordenadas',
        ),
        migrations.AddField(
            model_name='figura',
            name='capa_importada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.capa_importada'),
        ),
        migrations.AddField(
            model_name='figura',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='figura',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.proyecto'),
        ),
        migrations.AddField(
            model_name='figura',
            name='tipo',
            field=models.CharField(blank=True, choices=[('usuario', 'Usuario'), ('importada', 'Importada')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='figura',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capa_importada',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas_importadas', to='EditorWebGeoespacial.proyecto'),
        ),
        migrations.AlterField(
            model_name='figura',
            name='subclasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EditorWebGeoespacial.subclasificacion'),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
