# Generated by Django 4.2.24 on 2025-11-18 19:53

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EditorWebGeoespacial', '0018_remove_figura_coordenadas_figura_capa_importada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=32719),
        ),
        migrations.AlterField(
            model_name='figura',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.proyecto'),
        ),
        migrations.AlterField(
            model_name='figura',
            name='tipo',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('importada', 'Importada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='figura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
