# Generated by Django 4.2.24 on 2025-11-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0019_alter_figura_geom_alter_figura_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa_importada',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capa_importada', to='EditorWebGeoespacial.proyecto'),
        ),
    ]
