# Generated by Django 4.2.24 on 2025-11-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0020_alter_capa_importada_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura',
            name='capa_importada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='EditorWebGeoespacial.capa_importada'),
        ),
    ]
