# Generated by Django 4.2.24 on 2025-11-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0021_alter_figura_capa_importada'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
