# Generated by Django 4.2.24 on 2025-11-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0022_proyecto_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclasificacion',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.subcategoria'),
        ),
    ]
