# Generated by Django 4.2.24 on 2025-11-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0023_alter_subclasificacion_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclasificacion',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EditorWebGeoespacial.subcategoria'),
        ),
    ]
