# Generated by Django 4.2.24 on 2025-11-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditorWebGeoespacial', '0024_alter_subclasificacion_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclasificacion',
            name='publica',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
